### ISSUE TITLE
Responsive problem ?

### ISSUE THREAD

**Issue by ludm** [technotarek/timeliner#12]
Hello,

I have built a page using this great tiemline, but I have noticed that responsive works on my PC when I resize the browser but on my smartphones it doesn't.
As an example you can go there : http://www.animage.org/chronologie/timeliner.html
The background is supposed to be red (for test) when under 768px large. It works on PC but not on my smartphones (and the fonts are tiny also). Is there a specific thing to do ?

Best regards,
ludm

**Comment by technotarek** [comment]
Hello -- You don't have any of the standard and required markup to make your page behave responsively. For example, at a minimum your page needs a meta tag along the lines of:

<meta name="viewport" content="width=device-width">

You may want to look into using something like the HTML5 Boilerplate or another markup template if you're not familiar with coding responsive sites. Good luck and thanks for using Timeliner.

tarek

**Comment by ludm** [comment]
Oups, sorry for my mistake and thank you for your help
