### ISSUE TITLE
overlapping events

### ISSUE THREAD

**Issue by keneso9** [technotarek/timeliner#14]
Hi,

Maybe I missed it, but haven't seen it in the examples, does it allow overlapping and daily events, i.e.
event-1 start march 9 2016 - end march 15 2016
event-2 start march 12 2016 - end march 19 2016

Thank you

**Comment by technotarek** [comment]
The UI is agnostic about the end dates of events, and the default UI displays all dates in a linear fashion such that the oldest is presented before anything more recent. It doesn't consider end dates at all. If I understand what you are asking for, you'd have to develop a new UI presentation that considers and renders overlapping time periods. Not exactly sure what that might look like for this plugin. You may want to consider one of the other timeline projects that people have created, as I'm pretty sure some of them do what you're asking.

**Comment by keneso9** [comment]
Thank you for the prompt reply.
Yes I think you got what I meant, and yes I have seen couple other timelines that do it, I like yours, just wanted to have more options for my actual project; I'll keep yours in mind for eventually some other project.
