### ISSUE TITLE
changing from open IDs to a common class?

### ISSUE THREAD

**Issue by Toccamonium** [technotarek/timeliner#17]
Hi Tarek,

thanks for this great script. Just one question about the option "startOpen". Is it possible to fill this just with one class instead of IDs? It would be easer to handle because I just have to put, lets say the class "start-open", in the regarding element and it would work. 

thx
Florian

**Comment by technotarek** [comment]
I see the benefit and think it would probably be an easy revision. Please consider taking a stab at it and then sending a pull request. Otherwise I'll add it to the potential future enhancement list.

**Comment by technotarek** [comment]
Resolved via v2.3 (6c199bd0065eb61a03d53fb45a0246843dd9cc16)

**Comment by Toccamonium** [comment]
great, thanks :)
