### ISSUE TITLE
Clicking on title at open timeline content, title gets bigger, closing follows on second click

### ISSUE THREAD

**Issue by Toccamonium** [technotarek/timeliner#19]
Hi Tarek,
your class update works almost perfect. I figured out that when you click the first time on an title like "Emmett Till" it just gets bigger. When I click the second time only then it disappears. Is that expected or is this is a bug? Actually it should hide the content on first click.

cheers
Florian

**Comment by technotarek** [comment]
Good catch, thanks. Resolved.
