### ISSUE TITLE
Veritical Line Does not render with proper markup

### ISSUE THREAD

**Issue by willhayslett** [technotarek/timeliner#20]
Hi @technotarek, 

I'm having a hard time getting the vertical line to appear when using the markup as noted in your demo/instructions. 

https://jsfiddle.net/c1uqpLqj/3/

As you can see in the above fiddle, the actual line on the timeline doesn't appear. However, the line does appear if I remove the opening div marker of the last .timeline-wrapper (`<div class="timeline-wrapper">`) from the markup (of course, this causes other issues):

https://jsfiddle.net/c1uqpLqj/2/

Any idea what's wrong here?

Thanks,

Will

**Comment by technotarek** [comment]
You can resolve this by adding a clear class to your css:

```
.clear {
clear:both;
}
```

Then, add a clearing break just before the final closing div:

```
...
<br class="clear">
</div><!-- /.timeline-container -->
...
```

In order for your JS fiddle to appear properly, you also need to provide valid background image references for the tick marks referenced in the style sheet.

**Comment by willhayslett** [comment]
That fixed it! Thank you, both for helping me with this and creating the plugin. Good work! 

Best, 

Will
