### ISSUE TITLE
not closing fully

### ISSUE THREAD

**Issue by halukkaramete** [technotarek/timeliner#26]
Hello, in the original demo, I've noticed that "hide all" cannot revert to the initial state. 

In this page ->
The Development of Timeliner.js ( https://technotarek.com/timeliner/timeliner.html )

scroll to the bottom timeliner and pay attention to the fact that there is nothing in between "Concept" & "Idea". But the moment you click on one of them, you can never get that initial state back, the state when there is nothing in between the concept and the idea. 

Is there a setting that forces it to not close fully to keep the headliner, always visible?

**Comment by technotarek** [comment]
Hi -- Indeed, you are correct. That demo was set up differently than any of the others with an additional level that can be expanded. Getting that particular timeline back to its original state is not currently possible. I don't have plans right now to add that feature, but I'd certainly entertain a pull request if you'd like to give it a try. It shouldn't be difficult, but then again I'd have to carefully review the markup and js to be sure. Thanks for the feedback.

**Comment by halukkaramete** [comment]
Dear Tarek,

Thank you for the reply. I decided to use your timeline. I've started
reading your documentation. But I cannot see the docs how to put in a
youtube video or a straight mp3 link. Your docs state easy inclusion of
various formats but cannot seem to locate that part.

I find the red part is very complicated: Is there a breakdown of this part?
How do you come up with the  IDs? what about placing a mp3 link straight to
my server?
Is the red part not your timeline but the lightbox and youtube embed stuff?
If so, I can understand why your docs won't get into it, cause that's
straight HTML.
Please confirm,

<div class="timeline-wrapper">
<h2 class="timeline-time"><span>timeline-time 2</span></h2>
<dl class="timeline-series">

<dt id="19550828" class="timeline-event start-open"><a>timeline-event
start-open > a </a></dt>
<dd class="timeline-event-content" id="19550828EX">
<h3>timeline-event-content > h3</h3>

<div class="media">
<a href="#inline-1955-08-282" class="CBmodal"><img src="
http://img.youtube.com/vi/GU1wuqyOP98/0.jpg" width="240" height="180"
alt="Related
Video: The Emmett Till Murder"></a>
<p class="mediaLink"><a href="#inline-1955-08-282" class="CBmodal"
title="Related
Video: The Emmett Till Murder">Watch: The Emmett Till Murder</a></p>
<div style="display:none">
<div id="inline-1955-08-282" class="modalBox">
<object>
<param name="movie" value="
http://www.youtube.com/v/GU1wuqyOP98?fs=1&amp;hd=0&amp;showsearch=0&amp;showinfo=0&amp;width=640&amp;height=380
">
<param name="allowFullScreen" value="true">
<param name="allowScriptAccess" value="always">
<embed src="
http://www.youtube.com/v/GU1wuqyOP98?fs=1&amp;hd=0&amp;showsearch=0&amp;showinfo=0&amp;width=640&amp;height=380
<http://www.youtube.com/v/GU1wuqyOP98?fs=1&hd=0&showsearch=0&showinfo=0&width=640&height=380>"
type="application/x-shockwave-flash" allowfullscreen="true"
allowscriptaccess="always" width="640" height="380">
</object>
</div>
</div>
</div>

<p>
timeline-event-content > p (Above there is a lot of interlinking to get a
youtube video up there. #inline id worries me.) </p>

<br class="clear">
</dd>

<dt id="19551201" class="timeline-event"><a>timeline-event > 2</a></dt>
<dd class="timeline-event-content" id="19551201EX">
<h3>timeline-event-content > h3 </h3>
<p>
timeline-event-content > p </p>

<br class="clear">
</dd>
</dl>
</div>

**Comment by technotarek** [comment]
That's correct, the video media is displayed using the ColorBox plugin. You should refer to that plugin, or your modal plugin of choice, for more documentation. I also highly recommend that you use version 2.0 and the latest demo at https://technotarek.com/timeliner/demo-future/timeliner-future.html as your code reference. Unfortunately, I can no longer support or troubleshoot the older version.

**Comment by halukkaramete** [comment]
I will stick to version 2.0, but it looks like the link for the following
is missing in action?
TELEPORTATION

**Comment by halukkaramete** [comment]
Also all the links under this. Are you aware of it? or is it me who fails
to get those destinations? Your vimeo link works though. But the rest comes
with a white lighbox overlay with nothing in it.

AGED URBANITY
