### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by candidobugarin** [technotarek/timeliner#27]
Hello!

I would like to know how to correctly apply the responsive template to the timeline. On the desktop our project is in agreement however in the cell phone it bursts a little the sides (http://bugarintecnologia.rio/vasco/). Do you know how we can do it?

**Comment by technotarek** [comment]
Unfortunately, as a team of one, I can't provide implementation support. I encourage you to double check your code and compare it to the most recent demo. You may also want to consider posting your question on StackOverflow to see if someone from the community can help. Good luck and thanks for checking out Timeliner.
